ProductieSysteem/ProductieSysteem/Controllers/ProductieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProductieSysteem.Models;


namespace ProductieSysteem.Controllers
{
    public class ProductieController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductieOpgeven()
        {
            ViewData["Message"] = "Productie opgeven";
           // return View();
                List<SelectListItem> items = new List<SelectListItem>();

                items.Add(new SelectListItem { Text = "  ", Value = "0" });
                items.Add(new SelectListItem { Text = "Komkommer", Value = "1" });
                items.Add(new SelectListItem { Text = "Tomaat", Value = "0" });
                items.Add(new SelectListItem { Text = "Paprika", Value = "0" });



                ViewBag.Dagdelen = items;
                return View();
        }


        public ActionResult ProductieBijstellen()
        {
            ViewData["Message"] = "Productie bijstellen";
            return View();
        }
    }
}

ProductieSysteem/ProductieSysteem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ProductieSysteem", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inloggen", "Login", "Account")</li>
                    <li>@Html.ActionLink("Uitloggen", "LogOut", "Account")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

ProductieSysteem/ProductieSysteem/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>


    <div id="wrapper">
       
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                     ProductieSysteem
                    </a>
                </li>
                <li>
                    <a href="#">Dashboard</a>
                </li>
                <li>
                    @Html.ActionLink("Verwachte productie opgeven", "ProductieOpgeven", "Productie")
                </li>
                <li>
                    @Html.ActionLink("Verwachte productie bijstellen", "ProductieBijstellen", "Productie")
                </li>                
                <li>
                    <a href="#">Instellingen</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
                <li>
                    @Html.ActionLink("Uitloggen", "LogOut", "Account")
                </li>
                

            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                       @RenderBody()
                        
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>

</body>

</html>
